# Generated by Django 3.2.9 on 2021-11-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_alter_user_website_emailid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_website',
            name='institute_status',
            field=models.BooleanField(default=False),
        ),
    ]
