# Generated by Django 3.2.9 on 2021-11-25 03:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_id', models.IntegerField()),
                ('test_start', models.DateField(default=datetime.datetime(2021, 11, 25, 9, 21, 50, 593805))),
                ('number_question', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('total_marks', models.IntegerField()),
                ('batch_code', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.IntegerField()),
                ('question_type', models.IntegerField()),
                ('marks', models.IntegerField()),
                ('time', models.TimeField()),
                ('question', models.TextField(max_length=10000)),
                ('answere', models.CharField(default='', max_length=100)),
                ('option_a', models.CharField(max_length=100)),
                ('option_b', models.CharField(max_length=100)),
                ('option_c', models.CharField(max_length=100)),
                ('option_d', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('marks_obtain', models.IntegerField()),
                ('question_left', models.IntegerField(default=0)),
                ('question_attempt', models.IntegerField(default=0)),
                ('question_wrong', models.IntegerField(default=0)),
            ],
        ),
    ]
