# Generated by Django 3.2.9 on 2021-11-24 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answere',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='paper',
            name='test_start',
            field=models.DateField(default=datetime.datetime(2021, 11, 24, 18, 47, 24, 535106)),
        ),
    ]
