# Generated by Django 3.2.9 on 2021-11-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0005_auto_20211125_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='test_start',
            field=models.CharField(default='2021-11-25 13:02:09.877793', max_length=100),
        ),
    ]
