# Generated by Django 3.2.9 on 2021-11-20 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='institute_code',
        ),
        migrations.AlterField(
            model_name='user',
            name='institute_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Institute.institute'),
        ),
    ]
