# Generated by Django 3.2.9 on 2021-11-20 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0002_auto_20211120_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batches',
            fields=[
                ('batch_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('batch_name', models.CharField(max_length=20)),
                ('institute_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Institute.institute')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='batch_code',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Institute.batches'),
        ),
    ]
