# Generated by Django 3.2.9 on 2021-11-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0004_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='institute_code',
            field=models.CharField(max_length=7),
        ),
    ]
