# Generated by Django 3.2.9 on 2021-11-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0005_alter_institute_institute_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batches',
            name='institute_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='institute',
            name='admin_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='admin_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='batch_code',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='institute_id',
            field=models.IntegerField(),
        ),
    ]
