# Generated by Django 3.2.9 on 2021-11-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0006_auto_20211120_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batches',
            name='batch_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
